name: DDF Property Sync

on:
  schedule:
     - cron: '0 13 * * *'   # 9:00 AM ET
  workflow_dispatch:

jobs:
  fetch-and-save:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run DDF fetch script
        run: node fetch-property.js
        env:
          SUPABASE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
