name: Refresh City Views

on:
  schedule:
    - cron: '30 13 * * *'  # 9:30 AM ET
  workflow_dispatch:       # allows manual run

jobs:
  refresh-views:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install psql client
        run: sudo apt-get install -y postgresql-client

      - name: Refresh Materialized Views
        env:
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
        run: |
          psql "$SUPABASE_DB_URL" <<EOF
          REFRESH MATERIALIZED VIEW city_listings_full;
          REFRESH MATERIALIZED VIEW city_listings_full_fast;
          EOF

